# SubSpec SD (v1) without offloading (HQQ quantization only)
method: subspec_sd_no_offload

llm_path: meta-llama/Llama-3.1-8B-Instruct

recipe:
  class_path: specdecodes.helpers.recipes.subspec.hqq_4bit_attn_4bit_mlp_no_offload:Recipe

max_length: 4096
cache_implementation: static
warmup_iter: 1
compile_mode: max-autotune

generator_profiling: true

generator_kwargs:
  prefill_chunk_size: 4096

draft_params:
  temperature: 0.2
  max_depth: 32
  topk_len: 6
